// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ23wVir7cL8427ZA5pC2WvV2UP0WzP78',
    appId: '1:910737816468:web:b69a2843b48ad189332d81',
    messagingSenderId: '910737816468',
    projectId: 'medtrack-app-5f07d',
    authDomain: 'medtrack-app-5f07d.firebaseapp.com',
    storageBucket: 'medtrack-app-5f07d.firebasestorage.app',
    measurementId: 'G-SCM5EP9WEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8x70QAIeUKeTBi3tBcD-9g5fMNvhtd98',
    appId: '1:910737816468:android:cada0f13459077c9332d81',
    messagingSenderId: '910737816468',
    projectId: 'medtrack-app-5f07d',
    storageBucket: 'medtrack-app-5f07d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuQMjBblfkE6Y_FW5gd2A9eJ3vwB2fNds',
    appId: '1:910737816468:ios:be5c23fe01afab6c332d81',
    messagingSenderId: '910737816468',
    projectId: 'medtrack-app-5f07d',
    storageBucket: 'medtrack-app-5f07d.firebasestorage.app',
    iosClientId: '910737816468-rki47iq1e6raj9tcnof0u8hiep6h4lir.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuQMjBblfkE6Y_FW5gd2A9eJ3vwB2fNds',
    appId: '1:910737816468:ios:be5c23fe01afab6c332d81',
    messagingSenderId: '910737816468',
    projectId: 'medtrack-app-5f07d',
    storageBucket: 'medtrack-app-5f07d.firebasestorage.app',
    iosClientId: '910737816468-rki47iq1e6raj9tcnof0u8hiep6h4lir.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJ23wVir7cL8427ZA5pC2WvV2UP0WzP78',
    appId: '1:910737816468:web:28ab79d352e2b621332d81',
    messagingSenderId: '910737816468',
    projectId: 'medtrack-app-5f07d',
    authDomain: 'medtrack-app-5f07d.firebaseapp.com',
    storageBucket: 'medtrack-app-5f07d.firebasestorage.app',
    measurementId: 'G-Z9G05YS67V',
  );
}
